# Generated by Django 3.1.5 on 2021-01-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsAndCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField(verbose_name='Название счета')),
                ('balance_on_start', models.IntegerField(verbose_name='Баланс на старте')),
                ('credit_limit', models.PositiveIntegerField(verbose_name='Кредитный лимит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(verbose_name='Название типа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('withdrawal_amount', models.PositiveIntegerField(verbose_name='Сумма списания')),
                ('deposit_amount', models.PositiveIntegerField(verbose_name='Сумма пополнения')),
                ('from_the_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='base.accountsandcards', verbose_name='Со счёта')),
                ('on_the_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='base.accountsandcards', verbose_name='На счёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.TextField(verbose_name='Название вида')),
                ('regularity', models.CharField(choices=[('WE', 'Week'), ('MO', 'Mounth')], max_length=2, null=True)),
                ('is_income', models.BooleanField(verbose_name='Это доход?')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.referencetypes', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsandcards', verbose_name='Счёт')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.referenceviews', verbose_name='Доход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPlanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.PositiveIntegerField(verbose_name='План')),
                ('fact', models.PositiveIntegerField(verbose_name='Факт')),
                ('result_of_week', models.IntegerField(null=True, verbose_name='Результат недели')),
                ('financial_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.financialplan')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsandcards', verbose_name='Счёт')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.referenceviews', verbose_name='Расход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('date_buy', models.DateTimeField(verbose_name='Дата покупки')),
                ('service_time', models.PositiveIntegerField(verbose_name='Срок гарантии')),
                ('sum_final', models.PositiveIntegerField(verbose_name='Отложено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
