# Generated by Django 3.1.5 on 2021-01-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsandcards',
            options={'verbose_name': 'Счет(карта)', 'verbose_name_plural': 'Счета и карты'},
        ),
        migrations.AlterModelOptions(
            name='depreciations',
            options={'verbose_name': 'Амортизация', 'verbose_name_plural': 'Амортизация'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='financialplan',
            options={'verbose_name': 'Финплан', 'verbose_name_plural': 'Финплан'},
        ),
        migrations.AlterModelOptions(
            name='financialplanitems',
            options={'verbose_name': 'Финплан(пункт)', 'verbose_name_plural': 'Финплан(пункт)'},
        ),
        migrations.AlterModelOptions(
            name='incomes',
            options={'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
        migrations.AlterModelOptions(
            name='referencetypes',
            options={'verbose_name': 'Справочник(Тип)', 'verbose_name_plural': 'Справочник(Типы)'},
        ),
        migrations.AlterModelOptions(
            name='referenceviews',
            options={'verbose_name': 'Справочник(Вид)', 'verbose_name_plural': 'Справочник(Виды)'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name': 'Перемещение', 'verbose_name_plural': 'Перемещения'},
        ),
    ]
