# Generated by Django 3.1.5 on 2021-01-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210110_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='expense',
            new_name='income',
        ),
    ]
